config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/profile", to: "users#profile", as: :profile

  resources :places, only: [:index, :show, :new, :create] do
    member do
      get 'congrats_on_alerting'
    end

    collection do
      get "geolocate_user"
    end
    resources :missions, only: [:create]
  end

  resources :missions, only: [:edit, :update] do
    member do
      get 'review'
      patch 'complete'
      patch 'cancel'
      get 'congrats_on_completion'
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places, foreign_key: :mapmaster_id
  has_many :missions, foreign_key: :captaingreen_id

  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?

  mount_uploader :avatar, AvatarUploader

  LEVELS = %w[rookie apprentice champion hero legend]

  validates :username, presence: true, uniqueness: true, allow_blank: false
  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false
  validates :city, presence: true
  validates :zip_code, presence: true, format: { with: /\A([0-9]{5})|(2[AB]\d{3})\z/ }
  validates :country, presence: true
  validates :level, inclusion: { in: LEVELS }

  private

  def full_address
    "#{zip_code} #{city}, #{country}"
  end

  def full_address_changed?
    will_save_change_to_city? || will_save_change_to_zip_code? || will_save_change_to_country?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
    @next_missions = current_user.missions.where("date >= ? AND status NOT IN (?) OR status = ?", Date.today, ['completed', 'cancelled'], nil).order(:date)
    if @user.points <= 0 && @user.points <= 10
      @user.level = "rookie"
    elsif @user.points > 10 && @user.points <= 50
      @user.level = "apprentice"
    elsif @user.points > 50 && @user.points <= 100
      @user.level = "champion"
    elsif @user.points > 100 && @user.points <= 200
      @user.level = "hero"
    elsif @user.points > 200
      @user.level = "legend"
    end
  end

  private

  def params_user
    params.require(:user).permit(:level)
  end
end

app/views/users/profile.html.erb
<div class="profile-page">
  <!-- banner profile -->
    <!-- photo de profile -->
  <div class="banner">
    <%= link_to root_path do %>
      <%= image_tag "icons/Logo.png", class:"logo" %>
    <% end %>


    <div class="avatar-profile-medal">
      <%= cl_image_tag @user.avatar, alt: "#{@user}'s avatar" , class:"avatar" %>
      <!-- badge de level -->
      <div class="profile-medal">
        <% if @user.level == "legend" %>
          <%= image_tag "icons/legend_icon.png"%>
        <% elsif @user.level == "hero" %>
          <%= image_tag "icons/hero_icon.png"%>
        <% elsif @user.level == "champion" %>
          <%= image_tag "icons/badge_icon.png"%>
        <% elsif @user.level == "apprentice" %>
          <%= image_tag "icons/apprentice_icon.png"%>
        <% else @user.level == "rookie"%>
          <%= image_tag "icons/rookie_icon.png"%>
        <% end %>
      </div>
      <div class="profile-status-info">
        <% if @user.level == "legend" %>
          <p>Legend</p>

        <% elsif @user.level == "hero" %>
          <p>Hero</p>
        <% elsif @user.level == "champion" %>
          <p>Champion</p>

        <% elsif @user.level == "apprentice" %>
          <p>Apprentice</p>

        <% else @user.level == "rookie"%>
          <p>Rookie</p>

        <% end %>
      </div>
    </div>
  </div>


  <div class="profile-icons-info">
    <!-- mission-box -->
    <!-- count where user = captaingreen -->
    <div class="profile-icon">
      <%= @user.missions.count %>
      <%= image_tag "icons/bin_profile_icon.svg", class: "profile-icon-medals-info"%>
    </div>
    <!-- count where user = mapmaster -->
    <div class="profile-icon">
      <%= @user.places.count %>
      <%= image_tag "icons/marker_profile_icon.svg", class: "profile-icon-medals-info"%>
    </div>
    <div class="profile-icon">
      <%= @user.points %>
      <%= image_tag "icons/points_profile_icon.svg", class: "profile-icon-medals-info"%>
    </div>
    <!-- count points  -->
  </div>


  <div class="global-next-mission-card">
    <% if @next_missions %>
      <h3>Your next missions</h3>
      <!-- <p class="text-center">at</p> -->
      <% @next_missions.each do |next_mission| %>
        <div class="next-mission-place-address">
          <p><i class="fas fa-map-marker-alt"></i> <%= next_mission.place.address %></p>
        </div>

        <div class="next-mission-photo-buttons">
          <!-- img display -->
          <div class="right-part-next-mission">
            <div class="next-mission-image">
              <%= cl_image_tag next_mission.place.mapmaster_photo, alt: "#{next_mission.place.address}", class:'next-mission-photo' %>
            </div>
            <div class="day-time-slot">
              <p><i class="far fa-calendar-alt"></i> <%= next_mission.date.strftime("%d %m %Y") %></p>
              <!-- time_slot -->
              <p><i class="far fa-clock"></i>  <%= next_mission.time_slot.capitalize %></p>
            </div>
          </div>

          <div class="next-mission-buttons">
            <!-- section action -->
            <!-- button more info redirecting towards show of place -->
            <!--link_to @next_mission.place_path -->
            <%= link_to "more info", place_path(next_mission.place), class:'nav-btn green-btn next-mission-options' %>
            <!-- button completed redirecting towards the end of mission -->
            <%= link_to "complete", review_mission_path(next_mission), class:'nav-btn green-btn next-mission-options'%>
            <!-- button cancel delete mission and delete user_id from the place db -->
            <%= link_to "cancel", cancel_mission_path(next_mission), method: :patch, class:'nav-btn orange-btn next-mission-options'%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- past missions data (scroll)-->

    <!-- past mission card -->
  <div class="past_mission_card">
    <% if @user.missions.nil? %>
      <p>You don't have a mission history yet.</p>
      <p>Go on a mission or locate a point to see something here </p>
    <% else %>

      <div class="mission-completed-cards">
        <h3>Your past missions</h3>
        <% @user.missions.each do |mission| %>
          <div class="one-place-profile-card">
            <% if mission.status == "completed" %>

                <h4><i class="far fa-calendar-alt"></i> <%= mission.date.strftime("%d %m %Y") %> <strong>as CaptainGreen</strong></h4>
                <div class="memorypic-container">
                  <%= cl_image_tag mission.mapmaster_photo, class: 'memorypic'%>
                </div>
                 <%#= mission.place.volume %>
                <div class="volume-address">
                  <p><i class="fas fa-map-marker-alt"></i> <%= mission.place.address %></p>
                </div>
            <% end %>
          </div>
        <% end %>
      </div>



      <div class="place-profile-cards">
        <% @user.places.each do |place| %>
          <div class="one-place-profile-card">
            <h4><i class="far fa-calendar-alt"></i> <%= place.created_at.strftime("%d %m %Y") %> <strong>as MapMaster</strong></h4>
            <div class="memorypic-container">
              <%= cl_image_tag place.mapmaster_photo, class: 'memorypic' %>
            </div>
            <div class="volume-address">
            <%#= place.volume %>
            <p><i class="fas fa-map-marker-alt"></i> <%= place.address %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>