config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/profile", to: "users#profile", as: :profile

  resources :places, only: [:index, :show, :new, :create] do
    member do
      get 'congrats_on_alerting'
    end

    collection do
      get "geolocate_user"
    end
    resources :missions, only: [:create]
  end

  resources :missions, only: [:edit, :update] do
    member do
      get 'review'
      patch 'complete'
      patch 'cancel'
      get 'congrats_on_completion'
    end
  end


end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :captaingreen, class_name: "User"
  belongs_to :place

  TIME = %w[morning afternoon all-day]
  STATUS = %w[planned cancelled completed]

  validates :date, presence: true, on: :create
  validates :time_slot, presence: true, inclusion: { in: TIME }, on: :create
  validates :perceived_effort, presence: true, inclusion: { in: 1..5 }, numericality: { only_integer: true }, on: :update, if: :status_completed?

  # validates :participation_proof, presence: true, on: :update
  # validates :mapmaster_photo, presence: true, on: :update

  #validates :equipment, inclusion: { in: EQUIPMENT }

  mount_uploader :mapmaster_photo, PhotoUploader
  mount_uploader :participation_proof, PhotoUploader

  private

  def status_completed?
    status == "completed"
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:review, :complete, :cancel]

  def create
    @mission = Mission.new(mission_params)
    @place = Place.find(params[:place_id])
    @mission.place = @place
    @mission.captaingreen = current_user

    if @mission.save
      redirect_to profile_path
    else
      @markers = [
        {
          lat: @place.latitude,
          lng: @place.longitude,
          # infoWindow: render_to_string(partial: "info_window", locals: { place: @place })
          image_url: helpers.asset_url('icons/red_mapmarker_icon.png')
        }
      ]

      render 'places/show'
    end
  end

  def cancel
    @mission = Mission.find(params[:id])
    @mission.status = "cancelled"
    @mission.save
    redirect_to profile_path
  end

  def review
  end

  def complete
    @mission.update(mission_update_params)

    #update status mission
    @mission.status = "completed"

    # calculates the points for new mission

    progress = (@mission.place.volume - @mission.volume_left)
    if progress < 0
      @mission.mission_points = (@mission.perceived_effort - progress) * 10
    else
      @mission.mission_points = (@mission.perceived_effort + progress) * 10
    end

    @mission.save!

    # update total user points after mission
    current_user.points += @mission.mission_points
    current_user.save

    # update place volume with new volume left on site estimated by volonteer
    @mission.place.volume = @mission.volume_left
    @mission.place.save


    redirect_to congrats_on_completion_mission_path
  end

  def congrats_on_completion
    @mission = Mission.find(params[:id])
  end

  private

  def set_mission
    @mission = Mission.find(params[:id])
  end

  def mission_params
    params.require(:mission).permit(:date, :time_slot, :status)
  end

  def mission_update_params
    params.require(:mission).permit(:mapmaster_photo, :perceived_effort, :participation_proof, :volume_left)
  end
end

app/views/missions/congrats_on_completion.html.erb
<div class="thank-you-box">

  <h1>Thank you</h1>

  <h2>Your contribution means the world to us. As a <strong>thank you</strong> gift, we're delighted to award you</h2>


  <div class="thank-you-message">
    <%= image_tag "icons/yellow_trophy_icon.png", class: "trophy-mission" %>
    <p class="message-points"><span class="win-points"><%= @mission.mission_points %></span> points</p>
  </div>

  <h2 class="congratulations-message">Congratulations dear CaptainGreen !</h2>
  <%= image_tag'icons/bin_profile_icon.svg', class: "bin-mission-congratulations" %>

  <%= link_to 'Back to profile', profile_path, class: "nav-btn green-btn go-on-mission-button go-on-mission-button-show back-to-profile-button congrats-mission" %>

</div>

app/views/missions/review.html.erb
  <!-- banner MISSION COMPLETE -->
<div class="review-global-container">
  <div class="header update-mission">
    <h1>MISSION COMPLETE</h1>
  </div>

  <!-- box instructions -->
  <div class="instructions">
    <p>
      Thank you so much for your contribution! <br>
      Yet, all missions need a report! <br>
      Fortunately it will take less than 1 minute.
    </p>
  </div>

  <!-- form details -->
  <div class="new-form">

    <div class="typewriter">
      <p>Well done! Our nature is safe with you! <i class="fas fa-heart"></i> </p>
    </div>

    <%= simple_form_for @mission, url: complete_mission_path(@mission) do |f| %>
      <h2 class="text-title-form show-us-your-loot">Show us your loot!</h2>

      <label for="mission_mapmaster_photo" class="picture-mapmaster">
          <%= image_tag'icons/alert_page_icon.png', class: "camera mapmaster" %>
          <%= image_tag'icons/green_success_icon.png', class: "green-success mapmaster-photo hidden" %>
          <%= image_tag'icons/red_cross_error.png', class: "error-no-picture mapmaster hidden" %>
          <p class="take-picture-message mapmaster">Take a picture of trashpoint and upload it right here.</p>
          <p class="well-done hidden">Great! You're now two steps away from completing your mission!</p>
          <p class="error-picture-message mapmaster hidden">Dear CaptainGreen, we need your picture! </p>
      </label>

        <%= f.input :mapmaster_photo, label: false, input_html: { class: 'hidden' } %>
        <%= f.input :mapmaster_photo_cache, as: :hidden %>

      <h2 class="text-title-form quantity">HOW WAS THE BATTLE?</h2>

      <div class="volume-level-selection-wrapper">
        <label for="participation-level-1">1</label>
        <label for="participation-level-2">2</label>
        <label for="participation-level-3">3</label>
        <label for="participation-level-4">4</label>
        <label for="participation-level-5">5</label>

        <input type="radio" id="participation-level-1" value="1" name="mission[perceived_effort]" class="hidden">
        <input type="radio" id="participation-level-2" value="2" name="mission[perceived_effort]" class="hidden">
        <input type="radio" id="participation-level-3" value="3" name="mission[perceived_effort]" class="hidden">
        <input type="radio" id="participation-level-4" value="4" name="mission[perceived_effort]" class="hidden">
        <input type="radio" id="participation-level-5" value="5" name="mission[perceived_effort]" class="hidden">
      </div>

      <div class="legends-form">
        <p>I was barely exercising!</p>
        <p>I gave it my all!</p>
      </div>

      <h2 class="text-title-form volume-left">HOW DOES THE PLACE LOOK LIKE NOW?</h2>

      <div class="place_after-level-selection-wrapper">
        <label for="volume_left-level-1">1</label>
        <label for="volume_left-level-2">2</label>
        <label for="volume_left-level-3">3</label>
        <label for="volume_left-level-4">4</label>
        <label for="volume_left-level-5">5</label>

        <input type="radio" id="volume_left-level-1" value="1" name="mission[volume_left]" class="hidden">
        <input type="radio" id="volume_left-level-2" value="2" name="mission[volume_left]" class="hidden">
        <input type="radio" id="volume_left-level-3" value="3" name="mission[volume_left]" class="hidden">
        <input type="radio" id="volume_left-level-4" value="4" name="mission[volume_left]" class="hidden">
        <input type="radio" id="volume_left-level-5" value="5" name="mission[volume_left]" class="hidden">
      </div>

      <div class="legends-form">
        <p>it is all clean!</p>
        <p>Is is a real mess!</p>
      </div>

      <h2 class="text-title-form show-us-the-result">Show us the result!</h2>

        <label for="mission_participation_proof" class="picture-participation-proof">
          <%= image_tag'icons/alert_page_icon.png', class: "camera participation" %>
          <%= image_tag'icons/green_success_icon.png', class: "green-success proof hidden" %>
          <%= image_tag'icons/red_cross_error.png', class: "error-no-picture proof hidden" %>
          <p class="take-picture-message-participation">Take a picture of how clean it is now and upload it right here.</p>
          <p class="well-done-participation hidden">Dear Captain Green, your mission is set to be a great success! <i class="fas fa-thumbs-up"></i> </p>
          <p class="error-picture-message proof hidden">Dear CaptainGreen, we need your picture! </p>
        </label>

      <%= f.input :participation_proof, label: false, input_html: { class: 'hidden' } %>
      <%= f.input :participation_proof_cache, as: :hidden %>

      <%= f.submit 'Mission accomplished', class: "nav-btn green-btn go-on-mission-button go-on-mission-button-show update-large", id: 'submit-mission-review' %>

    <% end %>

  </div>
</div>