config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/profile", to: "users#profile", as: :profile

  resources :places, only: [:index, :show, :new, :create] do
    member do
      get 'congrats_on_alerting'
    end

    collection do
      get "geolocate_user"
    end
    resources :missions, only: [:create]
  end

  resources :missions, only: [:edit, :update] do
    member do
      get 'review'
      patch 'complete'
      patch 'cancel'
      get 'congrats_on_completion'
    end
  end


end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :mapmaster, class_name: "User"
  has_many :missions

  scope :not_clean_yet, -> { where.not(volume: 0) }

  reverse_geocoded_by :latitude, :longitude do |place, results|
    geo = results.first
    place.address = "#{geo.city}, #{geo.postal_code}" if geo
  end
  after_validation :reverse_geocode
  # if: :should_geocode_by_address?

  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :mapmaster_photo, PhotoUploader

  STATUS = %w[new on-going clean]
  TRASHES = %w[plastic dangerous glass metal liquid organic electronic miscellaneous]

  CLEANUP_EQUIPMENT_NEEDED = ['gloves', 'trash bag', 'rake', 'wheelbarrow', 'litter picker', 'face mask']
  VOLUMES = 0..5

  TRANSPORT = %w[backpack car truck]

  validates :trashes_on_site, presence: true
  validates :volume, presence: true, inclusion: { in: VOLUMES }, numericality: { only_integer: true }

  # validates :status, presence: true, inclusion: { in: STATUS }

  def equipments
    equipments = []

    trashes_on_site.each do |trash|
      if trash.include?('plastic')
        equipments << 'trash bag'
        equipments << 'picker'
      elsif trash.include?('dangerous')
        equipments << 'trash bag'
        equipments << 'gloves'
        equipments << 'face mask'
      elsif trash.include?('glass')
        equipments << 'trash bag'
        equipments << 'gloves'
      elsif trash.include?('metal')
        equipments << 'trash bag'
        equipments << 'gloves'
      elsif trash.include?('liquid')
        equipments << 'trash bag'
        equipments << 'gloves'
      elsif trash.include?('organic')
        equipments << 'trash bag'
        equipments << 'picker'
      elsif trash.include?('electronic')
        equipments << 'wheelbarrow'
      elsif trash.include?('miscellaneous')
        equipments << 'trash bag'
        equipments << 'gloves'
        equipments << 'picker'
      end
    end

    return equipments.uniq
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    if params[:search].present?
      coordinates = Geocoder.coordinates(params[:search], lookup: :nominatim)
      @places = Place.near(coordinates).geocoded.not_clean_yet.order("created_at DESC")

      # @places = Place.near(params[:search], lookup: :nominatim).geocoded.not_clean_yet.order("created_at DESC")
    else
      @places = Place.geocoded.not_clean_yet.order("created_at DESC")
    end
  end

  def show
    @place = Place.find(params[:id])
    @mission = Mission.new

    @mission_user = @place.missions.find_by(status: 'planned', captaingreen: current_user)

    @markers = [
      {
        lat: @place.latitude,
        lng: @place.longitude,
        # infoWindow: render_to_string(partial: "info_window", locals: { place: @place })
        image_url: helpers.asset_url('icons/red_mapmarker_icon.png')
      }
    ]
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(params_places)
    @place.status = "new"
    @place.mapmaster = current_user
    @place.mapmaster.points += 10
    @place.mapmaster.save

    # COOKIE STUFF
    @place.longitude = cookies[:longitude]
    @place.latitude = cookies[:latitude]

    #testing
    puts "#{@place.longitude} #{@place.latitude}"

    if @place.save
      redirect_to congrats_on_alerting_place_path(@place)
    else
      render :new
    end
  end

  def geolocate_user
    p cookies[:latitude]
    p cookies[:longitude]
    @markers = [{lat: cookies[:latitude], lng: cookies[:longitude]}]
  end

  def congrats_on_alerting
    @place = Place.find(params[:id])
  end

  private

  def params_places
    params.require(:place).permit(:volume, :mapmaster_photo, :latitude, :longitude, trashes_on_site: [])
  end
end

app/views/places/congrats_on_alerting.html.erb
<div class="thank-you-box">

  <h1>Thank you</h1>
  <h2>Your contribution means the world to us. As a <strong>thank you</strong> gift, we're delighted to award you</h2>

  <div class="thank-you-message">

    <%= image_tag "icons/yellow_trophy_icon.png", class: "trophy-mission" %>
    <p class="message-points"><span class="win-points">10</span> points</p>

  </div>

  <h2 class="congratulations-message">Congratulations dear Mapmaster!</h2>
  <%= image_tag'icons/bin_profile_icon.svg' %>

  <%= link_to 'See my alert', place_path(@place), class: "big-button complete-button place" %>

</div>

app/views/places/geolocate_user.html.erb
<!-- BANNER -->
<div class="geolocate-global">
  <div class="header locate-place">
    <h1>POINT LOCATION</h1>
  </div>

  <div class="geolocation-box">

  <h2>Where's that nasty garbage?</h2>

  <!--   <div class="new-form"> -->
      <!-- CONSIGNES -->
  <!--     <div class = "position-geoloc"> -->
        <div class="instructions-steps">

          <div class="step">
            <%= image_tag "icons/step1gps_icon.svg", class: "icon-geolocalisation" %><p>We need to know where you are to <strong>track garbage location</strong></p>
          </div>

          <div class="step">
            <%= image_tag "icons/step2gps_icon.svg", class: "icon-geolocalisation" %><p><strong>Allow geolocalisation</strong> to advance to the next step</p>
          </div>

          <div class="step">
           <%= image_tag "icons/step3gps_icon.svg", class: "icon-geolocalisation" %><p class="tap-button-geolocalisation">Tap <span class="button-geolocalise-me tap-geolocate">Geolocate me</span> on the <strong>map</strong> below to geolocate the spot</p>
          </div>

        </div>
  <!--     </div> -->

      <!-- MAP <-->
      <div class="map-geoloc">
         <button  id="geolocate_me" class="geolocate-button nav-btn orange-btn go-on-mission-button go-on-mission-button-show geolocating-btn" data-next-page-url="<%= new_place_path %>" >Geolocate me</button>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<!-- put the search bar here after ! -->

<div class="index-global-container">
  <div class="header index-places" id = "just-sticky">
    <!-- <h1 class="find-places">FIND PLACES</h1> -->
    <%= form_tag places_path, method: :get do %>
      <div class="input-group md-form form-sm form-2 pl-0">
        <!-- <input class="form-control my-0 py-1 lime-border" type="text" placeholder="Find your next mission" aria-label="Search" name="search"> -->
        <%= text_field_tag :search,
            params[:search],
            class: "form-control my-0 py-1 lime-border opacity-search-bar",
            placeholder: "Find your next mission",
            id: 'search-by-location'
          %>
        <!-- <div class="input-group-append">
          <span class="input-group-text lime lighten-2" id="basic-text1"><i class="fas fa-search text-grey"
              aria-hidden="true"></i></span>
        </div> -->
      </div>
    <% end %>
  </div>
  <!-- if search results are empty  -->
  <% if @places.empty? %>
    <div class="sorry-box">
      <div class="sorry-message-box">
        <span class="sorry-message"><%= "Sorry, we don't know where this is!" %></span>
      </div>
      <div>
        <%= image_tag "icons/place_not_found_icon.png", class: "where"%>
      </div>
      <div class="sorry-message-box">
        <span class="sorry-message"><%= "Please, check your address again." %></span>
      </div>
    </div>
  <% else %>
    <!-- cards -->
    <div class="global-places-cards">

      <!-- <div class="card-index-place-infos"> -->
        <% @places.each do |place| %>

            <%= link_to place_path(place[:id]), class: "link-to-place" do %>
              <div class="card-place-infos">
                <div>
                  <%= cl_image_tag place.mapmaster_photo, alt: "Photo of the site", class: "image-index" %>
                </div>

                <div class="card-place-details">
                  <p class="address-place"><i class="fas fa-map-marker-alt"></i> <%= place.address %></p>

                  <div class="participants">
                    <%= image_tag "icons/team_icon.svg", class: "group" %>
                    <p class="number-of-participants"><strong><%= place.missions.count %></strong> CaptainGreen</p>
                  </div>

                  <div class="icons-volume-place">
                    <!-- condition : the volume emoticon in green -->
                    <% if place.volume == 1  %>
                      <%= image_tag "icons/level/level_one_trash.png", class: "icon-level-of-trash" %>

                    <% elsif place.volume == 2  %>
                      <%= image_tag "icons/level/level_two_trash.png", class: "icon-level-of-trash" %>

                    <% elsif place.volume == 3  %>
                      <%= image_tag "icons/level/level_three_trash.png", class: "icon-level-of-trash" %>

                    <% elsif place.volume == 4  %>
                      <%= image_tag "icons/level/level_four_trash.png", class: "icon-level-of-trash" %>

                    <% elsif place.volume == 5  %>
                      <%= image_tag "icons/level/level_five_trash.png", class: "icon-level-of-trash" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/places/new.html.erb
  <!-- banner TELL US MORE -->
<div class="header create-place">
  <h1>TELL US MORE</h1>
</div>

  <!-- box instructions -->
<div class="instructions">
  <p>
    Dear Mapmaster, your alert is almost complete!
    Take a minute to fill in the details.
    It will help our CaptainGreen prepare for their mission.
  </p>
</div>

  <!-- form details -->
<div class="new-form">
  <%= simple_form_for @place do |f| %>
    <h2 class="text-title-form">Show us what you've found!</h2>

    <label for="place_mapmaster_photo" class="picture-mapmaster">
        <%= image_tag'icons/alert_page_icon.png', class: "camera" %>
        <%= image_tag'icons/green_success_icon.png', class: "green-success hidden" %>
        <p class="take-picture-message">Take a picture of trashpoint and upload it right here.</p>
        <p class="well-done hidden">Well done! We promise we'll fight that garbage until the very end <i class="fas fa-dragon"></i> </p>
    </label>

      <%= f.input :mapmaster_photo, label: false, input_html: { class: 'hidden' } %>
      <%= f.input :mapmaster_photo_cache, as: :hidden %>

    <h2 class="text-title-form volume">How bad is the crime scene?</h2>

    <div class="volume-level-selection-wrapper">
      <label for="volume-level-1">1</label>
      <label for="volume-level-2">2</label>
      <label for="volume-level-3">3</label>
      <label for="volume-level-4">4</label>
      <label for="volume-level-5">5</label>

      <input type="radio" id="volume-level-1" value="1" name="place[volume]" class="hidden">
      <input type="radio" id="volume-level-2" value="2" name="place[volume]" class="hidden">
      <input type="radio" id="volume-level-3" value="3" name="place[volume]" class="hidden">
      <input type="radio" id="volume-level-4" value="4" name="place[volume]" class="hidden">
      <input type="radio" id="volume-level-5" value="5" name="place[volume]" class="hidden">
    </div>

    <div class="legends-form">
      <p>Quite a few plastic bags around here</p>
      <p>We've a landfill situation</p>
    </div>


    <h2 class="text-title-form kind-of-trash">What kind of trash is there?</h2>

    <div class="trash-type-selection-wrapper">
      <label for="trash-type-glass">
        <%= image_tag'icons/trash-types/glass.svg' %>
      </label>
      <label for="trash-type-metal">
        <%= image_tag'icons/trash-types/metal.svg' %>
      </label>
      <label for="trash-type-organic">
        <%= image_tag'icons/trash-types/organic.svg' %>
      </label>
      <label for="trash-type-plastic">
        <%= image_tag'icons/trash-types/plastic.svg' %>
      </label>
      <label for="trash-type-miscellaneous">
        <%= image_tag'icons/trash-types/miscellaneous.svg' %>
      </label>
      <label for="trash-type-electronic">
        <%= image_tag'icons/trash-types/electronic.svg' %>
      </label>
      <label for="trash-type-liquid">
        <%= image_tag'icons/trash-types/liquid.svg' %>
      </label>
      <label for="trash-type-dangerous">
        <%= image_tag'icons/trash-types/dangerous.svg' %>
      </label>

      <input type="checkbox" id="trash-type-glass"          value="glass" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-metal"          value="metal" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-organic"        value="organic" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-plastic"        value="plastic" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-miscellaneous"  value="miscellaneous" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-electronic"     value="electronic" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-liquid"         value="liquid" name="place[trashes_on_site][]" class="hidden">
      <input type="checkbox" id="trash-type-dangerous"      value="dangerous" name="place[trashes_on_site][]" class="hidden">
    </div>

    <%= f.submit 'Alert', class: "nav-btn orange-btn go-on-mission-button go-on-mission-button-show alert-large" %>

  <% end %>

</div>

<!-- navbar -->

app/views/places/show.html.erb
<div class="header show-place">
  <h1>GET MORE DETAILS</h1>
</div>

<div class="mission-show">
  <div class="mission-details">

    <!-- map -->
    <div
    id="map"
    style="width: 100%;
    height: 200px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    >

    <!-- photo du site -->
    <div class="mission-photo">
      <%= cl_image_tag @place.mapmaster_photo, alt: "Photo of the place", class:'place-photo' %>
    </div>

  </div>

    <div class="show-place-details">
      <p class="show-place-address"><i class="fas fa-map-marker-alt"></i> <%= @place.address %></p>

      <% if @place.volume == 1 %>
        <div class="trash-level-message-box">
          <%= image_tag "icons/level/level_one_trash.png", class: "icon-level-of-trash" %>
        </div>

      <% elsif @place.volume == 2 %>
        <div class="trash-level-message-box">
          <%= image_tag "icons/level/level_two_trash.png", class: "icon-level-of-trash" %>
        </div>

      <% elsif @place.volume == 3 %>
        <div class="trash-level-message-box">
          <%= image_tag "icons/level/level_three_trash.png", class: "icon-level-of-trash" %>
        </div>

      <% elsif @place.volume == 4 %>
        <div class="trash-level-message-box">
          <%= image_tag "icons/level/level_four_trash.png", class: "icon-level-of-trash" %>
        </div>

      <% elsif @place.volume == 5 %>
        <div class="trash-level-message-box">
          <%= image_tag "icons/level/level_five_trash.png", class: "icon-level-of-trash" %>
        </div>

      <% end %>

    </div>
    <hr>

    <div class="type-of-trashes">
      <p class="watch-out-message">Watch out!</p>
      <p>The Mapmaster reported a real mess!</p>

      <!-- place trash types -->
      <% @place.trashes_on_site.each do |trash| %>
        <%= image_tag "icons/trash-types/#{trash.parameterize(separator: '_')}.svg", class: "show-icon-trash" %>
      <% end %>
    </div>

    <hr>

    <!-- material suggestions -->
    <div class="bring-bloc">
      <p class="equipment-suggestions">You might need a bit of equipment:</p>

      <% @place.equipments.each do |equipment| %>
          <%= image_tag "icons/equipment/#{equipment.parameterize(separator: '_')}_icon.png", class: "icon-equipment" %>
      <% end %>
    </div>

    <% if @mission_user %>
     <p class="days-to-mission-count">Your mission is in <span class="days-to-mission"><%= (@mission_user.date - Date.today).to_i %></span> days</p>
    <% else %>
      <div class="go-on-mission-button">
      <button type="button" class="nav-btn green-btn go-on-mission-button go-on-mission-button-show join-mission-small" data-toggle="modal" data-target="#goOnMissionModal">
          GO ON MISSION
        </button>
      </div>
    <% end %>

    <!-- pop up de demande sur la date -->
    <% mission_has_errors = !@mission.errors.empty? %>
    <div class="modal fade" id="goOnMissionModal" data-has-errors="<%= mission_has_errors %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">

            <div class="modal-header-title"></div>
              <h1 class="modal-title" id="exampleModalLongTitle">Ready to go?</h1>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <%= simple_form_for [@place, @mission] do |f| %>

              <div class="modal-body">
                <%= f.input :date, as: :string, required: true, label: "Select date", input_html: { id: "datepicker" } %>

                <%= f.label :time_slot, required: true, label: "Select time slot" %>
                <% if @mission.errors['time_slot'].present? %>
                  <div class="form-group string required mission_date form-group-invalid">
                    <div class="invalid-feedback" style="display: block">Time slot <%= @mission.errors['time_slot'].first %></div>
                  </div>
                <% end %>

                <div class="time-slot-selection-wrapper">
                  <%= f.collection_radio_buttons :time_slot, Mission::TIME, :to_s, :capitalize %>
                </div>

              </div>

              <div class="modal-footer">
                <!-- <button type="button" class="nav-btn green-btn" data-dismiss="modal">Close</button> -->
                <%= f.submit value: "Submit", class: 'nav-btn green-btn', data: { disable_with: 'Submit' } %>
              </div>

            <% end %>

          </div>
        </div>
      </div>
  </div>
</div>

    <!-- safety tips -->
<div class="safety">
  <p>Because we<i class="fas fa-heart"></i> and care about you, please consider the following safety recommendations. Avoid contact with chemicals without gloves and be careful with sharp objects.</p>
</div>